# 异常处理

将可能会发生异常错误的代码放在try块里面，如果发生异常就会使用except进行捕捉，并执行except中的代码，最后无论是否发生异常，都会执行finally块中的代码。

如果发生了异常，那么try块中发生异常的代码之后的代码将不会被执行，且如果发生的异常没有任何一个except捕捉到，这个异常又会传递回try语句块中。

如果定义了多个except语句，它们就像条件判断中的elif一样，最多只会执行一个except块。

try...except...else...如果try语句中没有异常发生就会继续执行else中的语句，如果发生了异常就不会去执行else中的语句了。

```text
try:
    # 此处为可能会发生异常错误的代码，如果发生异常将会抛出异常
    pass
except ValueError as e:
    # 捕捉指定的异常ValueError，并取别名为e
    # 如果捕捉到指定的异常（如ValueError），就会在进入这里进行处理
    pass
except (TypeError, NameError):
    # 可以一次指定捕获多个异常，多个异常一元组形式指定即可
    pass
except:
    # 没有指定异常时，表示捕捉所有异常
    # 如果抛出的异常在前面所有指定的异常都没有捕捉到，那么就会进入这里，
    pass
finally:
    # 无论是否发生异常都会执行此处代码
    pass
```

## 编程建议：

* 在异常处理时尽量指定需要捕获的异常，虽然except不指定任何异常时可以捕获所有异常，但同时也可能是你错过某些异常（虽然程序没有报错，其实异常可能已经发生了）。
* 尽量使用finally来进行一些无论是否发生异常都要进行的“最后”的处理。

## 其他知识点：

* **打印异常信息：**可以使用trackback模块的format\_exc\(\)函数打印异常信息
* **抛出异常：**使用“raise MyError”来抛出异常，并在except捕获这个异常
* **自定义异常：**自定义的异常类，需要直接或间接继承Exception类，且一般以Error作为后缀



